name: XKCD cache update

on:
  schedule:
    - cron: "0 19 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync --extra build-cache

      - name: Rebuild caches
        run: |
          uv run python - <<'PY'
          import random
          from explainxkcd import ExplainXKCDScraper
          from embedding_search import EmbeddingCache

          scraper = ExplainXKCDScraper()
          scraper.hydrate_and_refresh_cache()
          explanations = scraper.load_cache()

          # Incremental embeddings: only embed comics missing from the index
          cache = EmbeddingCache()
          missing = [n for n in sorted(explanations.keys()) if not cache.has(str(n))]
          for n in missing:
              cache.get_or_compute(str(n), explanations[n])

          # Recompute embeddings for the last item in cache
          if explanations:
            last_comic = max(explanations.keys())
            cache.get_or_compute(str(last_comic), explanations[last_comic], force=True)

          # Force update ten random explanations
          if len(explanations) >= 10:
              random_comics = random.sample(list(explanations.keys()), 10)
              for comic_id in random_comics:
                  cache.get_or_compute(str(comic_id), explanations[comic_id], force=True)
          PY

      - name: Commit and push changes
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        run: |
          git config user.name "$GIT_AUTHOR_NAME"
          git config user.email "$GIT_AUTHOR_EMAIL"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore(cache): nightly update explainxkcd and embeddings"
            git push
          fi
